
services:
  postgres:
    image: postgres:15-alpine
    container_name: go_postgres_tasks_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminPassword
      POSTGRES_DB: todo-tasks
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
